# Site settings
title: Ege Adıgüzel
description: Undergraduate physics student
url: "https://egead.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
